# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "a-ponte-central-tfstate-704744419504"
    dynamodb_table = "a-ponte-lock-a-ponte"
    encrypt        = true
    key            = "a-ponte/terraform.tfstate"
    region         = "sa-east-1"
  }
}
